<root report="SLA" tenant="egi" details="level0" topology="">
    <report report="Critical" tenant="egi" description="Advanced Computing for Research" contact="argo-egi@mailman.egi.eu" url="http://egi.eu" topologyAR="NGI" topologyStatus="SITES" topologyReference="goc" topologyDetails="SITES" thresholdAv="80" thresholdRe="85">
        <group_count>30</group_count>
        <group_type>NGI</group_type>
        <group_list>
            <item>AfricaArabia</item>
            <item>AsiaPacific</item>
            <item>CERN</item>
            <item>NGI_AEGIS</item>
            <item>NGI_BG</item>
            <item>NGI_BY</item>
            <item>NGI_CH</item>
            <item>NGI_CHINA</item>
            <item>NGI_CZ</item>
            <item>NGI_DE</item>
            <item>NGI_FI</item>
            <item>NGI_FRANCE</item>
            <item>NGI_GRNET</item>
            <item>NGI_HR</item>
            <item>NGI_HU</item>
            <item>NGI_IBERGRID</item>
            <item>NGI_IL</item>
            <item>NGI_IT</item>
            <item>NGI_NDGF</item>
            <item>NGI_NL</item>
            <item>NGI_PL</item>
            <item>NGI_RO</item>
            <item>NGI_SI</item>
            <item>NGI_SK</item>
            <item>NGI_TR</item>
            <item>NGI_UA</item>
            <item>NGI_UK</item>
            <item>ROC_Canada</item>
            <item>ROC_LA</item>
            <item>Russia</item>
        </group_list>
        <endpoint_group_count>234</endpoint_group_count>
        <endpoint_group_type>SITES</endpoint_group_type>
        <endpoint_group_list>
            <item>100IT</item>
            <item>AEGIS01-IPB-SCL</item>
            <item>AEGIS02-RCUB</item>
            <item>AEGIS03-ELEF-LEDA</item>
            <item>AEGIS11-MISANU</item>
            <item>ARNES</item>
            <item>ATLAND</item>
            <item>AUVERGRID</item>
            <item>AZ-IFAN</item>
            <item>AstrogridPUC</item>
            <item>Australia-ATLAS</item>
            <item>Australia-T2</item>
            <item>BEIJING-LCG2</item>
            <item>BEgrid-BELNET</item>
            <item>BEgrid-ULB-VUB</item>
            <item>BG01-IPP</item>
            <item>BUDAPEST</item>
            <item>BY-NCPHEP</item>
            <item>BelGrid-UCL</item>
            <item>CA-SFU-T2</item>
            <item>CA-TRIUMF-T2K</item>
            <item>CA-VICTORIA-WESTGRID-T2</item>
            <item>CAMK</item>
            <item>CBPF</item>
            <item>CERN-PROD</item>
            <item>CESGA</item>
            <item>CESNET-MetaCloud</item>
            <item>CIEMAT-LCG2</item>
            <item>CIRMMP</item>
            <item>CLOUDIFIN</item>
            <item>CNR-ILC-PISA</item>
            <item>CREATIS-INSA-LYON</item>
            <item>CSC</item>
            <item>CSCS-LCG2</item>
            <item>CYFRONET-CLOUD</item>
            <item>CYFRONET-LCG2</item>
            <item>CYFRONET-PROMETHEUS</item>
            <item>DESY-HH</item>
            <item>DESY-ZN</item>
            <item>DZ-01-ARN</item>
            <item>EELA-UTFSM</item>
            <item>FI_AA</item>
            <item>FI_Aalto</item>
            <item>FI_HIP_T2</item>
            <item>FI_Helsinki</item>
            <item>FI_JYU</item>
            <item>FI_LUT</item>
            <item>FI_Oulu</item>
            <item>FI_TUT</item>
            <item>FI_UEF</item>
            <item>FI_UTU</item>
            <item>FMPhI-UNIBA</item>
            <item>FZJ</item>
            <item>FZK-LCG2</item>
            <item>GARR-01-DIR</item>
            <item>GR-07-UOI-HEPLAB</item>
            <item>GR-12-TEIKAV</item>
            <item>GRID-UNAM</item>
            <item>GRIDIFIN</item>
            <item>GRIF</item>
            <item>GRISU-UNINA</item>
            <item>GoeGrid</item>
            <item>HEPHY-UIBK</item>
            <item>HG-02-IASA</item>
            <item>HG-06-EKT</item>
            <item>HG-08-Okeanos</item>
            <item>HG-09-Okeanos-Cloud</item>
            <item>HK-HKU-CC-01</item>
            <item>HK-LCG2</item>
            <item>Hephy-Vienna</item>
            <item>ICM</item>
            <item>ICN-UNAM</item>
            <item>IEPSAS-Kosice</item>
            <item>IFCA-LCG2</item>
            <item>IFIC-LCG2</item>
            <item>IISAS-Bratislava</item>
            <item>IISAS-FedCloud</item>
            <item>IISAS-GPUCloud</item>
            <item>IISAS-Nebula</item>
            <item>IL-TAU-HEP</item>
            <item>IN-DAE-VECC-02</item>
            <item>IN2P3-CC</item>
            <item>IN2P3-CC-T2</item>
            <item>IN2P3-CPPM</item>
            <item>IN2P3-IPNL</item>
            <item>IN2P3-IRES</item>
            <item>IN2P3-LAPP</item>
            <item>IN2P3-LPC</item>
            <item>IN2P3-LPSC</item>
            <item>IN2P3-SUBATECH</item>
            <item>INDIACMS-TIFR</item>
            <item>INFN-BARI</item>
            <item>INFN-CATANIA</item>
            <item>INFN-CATANIA-STACK</item>
            <item>INFN-CNAF-LHCB</item>
            <item>INFN-COSENZA</item>
            <item>INFN-FERRARA</item>
            <item>INFN-FRASCATI</item>
            <item>INFN-GENOVA</item>
            <item>INFN-LECCE</item>
            <item>INFN-LNL-2</item>
            <item>INFN-MIB</item>
            <item>INFN-MILANO-ATLASC</item>
            <item>INFN-NAPOLI-ATLAS</item>
            <item>INFN-PADOVA</item>
            <item>INFN-PADOVA-STACK</item>
            <item>INFN-PISA</item>
            <item>INFN-ROMA1</item>
            <item>INFN-ROMA1-CMS</item>
            <item>INFN-ROMA3</item>
            <item>INFN-T1</item>
            <item>INFN-TORINO</item>
            <item>INFN-TRIESTE</item>
            <item>IR-IPM-HEP</item>
            <item>ITEP</item>
            <item>JINR-LCG2</item>
            <item>JINR-T1</item>
            <item>JP-KEK-CRC-02</item>
            <item>KR-KISTI-GSDC-01</item>
            <item>KR-KISTI-GSDC-02</item>
            <item>KR-KNU-T3</item>
            <item>Kharkov-KIPT-LCG2</item>
            <item>LRZ</item>
            <item>LRZ-LMU</item>
            <item>MA-01-CNRST</item>
            <item>MA-04-CNRST-ATLAS</item>
            <item>MPPMU</item>
            <item>NCBJ-CIS</item>
            <item>NCG-INGRID-PT</item>
            <item>NCP-LCG2</item>
            <item>NDGF-T1</item>
            <item>NGI_IT</item>
            <item>NIHAM</item>
            <item>NIKHEF-ELPROD</item>
            <item>OBSPM</item>
            <item>PSNC</item>
            <item>RAL-LCG2</item>
            <item>RECAS-BARI</item>
            <item>RECAS-NAPOLI</item>
            <item>RO-02-NIPNE</item>
            <item>RO-03-UPB</item>
            <item>RO-07-NIPNE</item>
            <item>RO-11-NIPNE</item>
            <item>RO-13-ISS</item>
            <item>RO-14-ITIM</item>
            <item>RO-16-UAIC</item>
            <item>RRC-KI</item>
            <item>RRC-KI-T1</item>
            <item>RU-Protvino-IHEP</item>
            <item>RU-SARFTI</item>
            <item>RU-SPbSU</item>
            <item>RWTH-Aachen</item>
            <item>Ru-Troitsk-INR-LCG2</item>
            <item>SAMPA</item>
            <item>SARA-MATRIX</item>
            <item>SCAI</item>
            <item>SE-SNIC-T2</item>
            <item>SUPERCOMPUTO-UNAM</item>
            <item>SiGNET</item>
            <item>T2-TH-SUT</item>
            <item>T2_Estonia</item>
            <item>T3_CH_PSI</item>
            <item>TASK</item>
            <item>TECHNION-HEP</item>
            <item>TOKYO-LCG2</item>
            <item>TR-03-METU</item>
            <item>TR-10-ULAKBIM</item>
            <item>TR-FC1-ULAKBIM</item>
            <item>TRIGRID-INFN-CATANIA</item>
            <item>TRIUMF-LCG2</item>
            <item>TU-Kosice</item>
            <item>TW-FTT</item>
            <item>TW-NCHC</item>
            <item>TW-NCUHEP</item>
            <item>TW-NTU-HEP</item>
            <item>Taiwan-LCG2</item>
            <item>UA-BITP</item>
            <item>UA-IFBG</item>
            <item>UA-IMBG</item>
            <item>UA-IRE</item>
            <item>UA-ISMA</item>
            <item>UA-KNU</item>
            <item>UA-MHI</item>
            <item>UA-NSCMBR</item>
            <item>UA-PIMEE</item>
            <item>UAM-LCG2</item>
            <item>UA_BITP_ARC</item>
            <item>UA_ICMP_ARC</item>
            <item>UA_ICYB_ARC</item>
            <item>UA_ILTPE_ARC</item>
            <item>UKI-LT2-Brunel</item>
            <item>UKI-LT2-IC-HEP</item>
            <item>UKI-LT2-QMUL</item>
            <item>UKI-LT2-RHUL</item>
            <item>UKI-NORTHGRID-LANCS-HEP</item>
            <item>UKI-NORTHGRID-LIV-HEP</item>
            <item>UKI-NORTHGRID-MAN-HEP</item>
            <item>UKI-NORTHGRID-SHEF-HEP</item>
            <item>UKI-SCOTGRID-DURHAM</item>
            <item>UKI-SCOTGRID-ECDF</item>
            <item>UKI-SCOTGRID-GLASGOW</item>
            <item>UKI-SOUTHGRID-BHAM-HEP</item>
            <item>UKI-SOUTHGRID-BRIS-HEP</item>
            <item>UKI-SOUTHGRID-CAM-HEP</item>
            <item>UKI-SOUTHGRID-OX-HEP</item>
            <item>UKI-SOUTHGRID-RALPP</item>
            <item>UKI-SOUTHGRID-SUSX</item>
            <item>UMB-BB</item>
            <item>UNI-BONN</item>
            <item>UNI-FREIBURG</item>
            <item>UNI-SIEGEN-HEP</item>
            <item>UNIBE-ID</item>
            <item>UNIBE-LHEP</item>
            <item>UNICPH-NBI</item>
            <item>UNIGE-DPNC</item>
            <item>UNINA-EGEE</item>
            <item>UPV-GRyCAP</item>
            <item>UPorto</item>
            <item>USC-LCG2</item>
            <item>WCSS64</item>
            <item>WEIZMANN-LCG2</item>
            <item>WUT</item>
            <item>ZA-CHPC</item>
            <item>ZA-WITS-CORE</item>
            <item>egee.irb.hr</item>
            <item>egee.srce.hr</item>
            <item>ifae</item>
            <item>mainz</item>
            <item>mainzgrid</item>
            <item>pic</item>
            <item>prague_cesnet_lcg2</item>
            <item>praguelcg2</item>
            <item>ru-PNPI</item>
            <item>wuppertalprod</item>
        </endpoint_group_list>
        <service_count>9</service_count>
        <service_list>
            <item>ARC-CE</item>
            <item>CREAM-CE</item>
            <item>GRAM5</item>
            <item>QCG.Computing</item>
            <item>SRM</item>
            <item>Site-BDII</item>
            <item>eu.egi.cloud.vm-management.occi</item>
            <item>org.openstack.nova</item>
            <item>unicore6.TargetSystemFactory</item>
        </service_list>
    </report>
    <report report="OPS-MONITOR-Critical" tenant="egi" description="Advanced Computing for Research" contact="argo-egi@mailman.egi.eu" url="http://egi.eu" topologyAR="NGI" topologyStatus="SITES" topologyReference="goc" topologyDetails="SITES" thresholdAv="80" thresholdRe="85">
        <group_count>1</group_count>
        <group_type>NGI</group_type>
        <group_list>
            <item>EGI.eu</item>
        </group_list>
        <endpoint_group_count>20</endpoint_group_count>
        <endpoint_group_type>SITES</endpoint_group_type>
        <endpoint_group_list>
            <item>EGI-DATAHUB</item>
            <item>EGI-MARKETPLACE</item>
            <item>GRIDOPS-ACCPORTAL</item>
            <item>GRIDOPS-APEL</item>
            <item>GRIDOPS-APPDB</item>
            <item>GRIDOPS-CATCHALL</item>
            <item>GRIDOPS-CSGF</item>
            <item>GRIDOPS-CTOOLS</item>
            <item>GRIDOPS-CheckIn</item>
            <item>GRIDOPS-DIRAC4EGI</item>
            <item>GRIDOPS-EC3</item>
            <item>GRIDOPS-GGUS</item>
            <item>GRIDOPS-GOCDB</item>
            <item>GRIDOPS-MSG</item>
            <item>GRIDOPS-OPSPORTAL</item>
            <item>GRIDOPS-PERUN</item>
            <item>GRIDOPS-SECTOOLS</item>
            <item>GRIDOPS-UMDREPO</item>
            <item>GRIDOPS-WS-PGRADE</item>
            <item>GRIDOPS-XGUS</item>
        </endpoint_group_list>
        <service_count>15</service_count>
        <service_list>
            <item>VOMS</item>
            <item>egi.APELRepository</item>
            <item>egi.AccountingPortal</item>
            <item>egi.AppDB</item>
            <item>egi.GGUS</item>
            <item>egi.GOCDB</item>
            <item>egi.MSGBroker</item>
            <item>egi.OpsPortal</item>
            <item>egi.Perun</item>
            <item>egi.Portal</item>
            <item>egi.aai.oidc</item>
            <item>egi.aai.saml</item>
            <item>egi.aai.tts</item>
            <item>org.onedata.oneprovider</item>
            <item>org.onedata.onezone</item>
        </service_list>
    </report>
    <report report="Critical" tenant="eudat" description="Collaborative Data Infrastructure" contact="argo-eudat@eudat.eu" url="http://eudat.eu" topologyAR="SERVICEGROUPS" topologyStatus="SERVICEGROUPS" topologyReference="dpmt" topologyDetails="SERVICES" thresholdAv="90" thresholdRe="95">
        <group_count>1</group_count>
        <group_type>PROJECT</group_type>
        <group_list>
            <item>EUDAT</item>
        </group_list>
        <endpoint_group_count>46</endpoint_group_count>
        <endpoint_group_type>SERVICEGROUPS</endpoint_group_type>
        <endpoint_group_list>
            <item>ARCHIVE-DPHEP-MPP</item>
            <item>B2ACCESS CDI</item>
            <item>B2ACCESS MYPROXY</item>
            <item>B2ACCESS-INTEGRATION</item>
            <item>B2ACCESS4EPOS</item>
            <item>B2ACCESS4LifeScience</item>
            <item>B2DROP CDI</item>
            <item>B2DROP WESTLIFE</item>
            <item>B2FIND CDI</item>
            <item>B2FIND ENES</item>
            <item>B2FIND IST</item>
            <item>B2FIND-EUROPEANA</item>
            <item>B2HANDLE CDI</item>
            <item>B2NOTE CDI</item>
            <item>B2SAFE ABC</item>
            <item>B2SAFE CLARIN AT</item>
            <item>B2SAFE CLARIN EKUT</item>
            <item>B2SAFE CLARIN REPLIX</item>
            <item>B2SAFE CLARIN SOAS</item>
            <item>B2SAFE ClimateModel</item>
            <item>B2SAFE EISCAT</item>
            <item>B2SAFE EPOS</item>
            <item>B2SAFE Herbadrop</item>
            <item>B2SAFE IST</item>
            <item>B2SAFE MfN</item>
            <item>B2SAFE VPH</item>
            <item>B2SAFE catch all</item>
            <item>B2SAFE-DIXA</item>
            <item>B2SHARE CDI</item>
            <item>B2SHARE JUELICH</item>
            <item>B2STAGE HybTurb3D</item>
            <item>B2STAGE MULTINANO</item>
            <item>B2STAGE SIMCODE</item>
            <item>B2STAGE SPHINX</item>
            <item>B2STAGE TURBASE</item>
            <item>B2STAGE-DSI-B2SAFE</item>
            <item>B2STAGE-GRIDFTP-Workspace</item>
            <item>CDI Community Service</item>
            <item>CDI Versioning Service</item>
            <item>CDI WEBPRESENCE</item>
            <item>CDI WIKI SERVICE</item>
            <item>CDI-ARGO-monitoring</item>
            <item>CDI-Accounting</item>
            <item>CDI-DPMT</item>
            <item>CDI-SPMT</item>
            <item>CDI-SVMON</item>
        </endpoint_group_list>
        <service_count>20</service_count>
        <service_list>
            <item>b2access.crowd</item>
            <item>b2access.myproxy</item>
            <item>b2access.oauth</item>
            <item>b2access.openid-bridge</item>
            <item>b2access.unity</item>
            <item>b2drop.nextcloud</item>
            <item>b2find.ckan</item>
            <item>b2gether.cms.drupal</item>
            <item>b2handle.handle.api</item>
            <item>b2note.fe</item>
            <item>b2safe.dsi</item>
            <item>b2safe.irods</item>
            <item>b2share.invenio</item>
            <item>eudat.cms.confluence</item>
            <item>eudat.coord.dpmt</item>
            <item>eudat.its.jira</item>
            <item>eudat.itsm.spmt</item>
            <item>eudat.monitoring</item>
            <item>eudat.rep.gitlab</item>
            <item>eudat.webpresence</item>
        </service_list>
    </report>
    <report report="Critical" tenant="sdc" description="Ocean and marine data management" contact="argo-sdc@sdc.eu" url="https://www.seadatanet.org" topologyAR="SERVICEGROUPS" topologyStatus="SERVICEGROUPS" topologyReference="goc-sdc" topologyD<?xml-stylesheet type='text/xsl' href='/template//app/html/error.html'?>
