<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><!-- generated by module html-template-engine --><xsl:output method="html"></xsl:output><xsl:variable name="app.version">2.1.6</xsl:variable><xsl:variable name="app.instance">prod</xsl:variable><xsl:template match="/"><html lang="en" xmlns:tpl="http://software.in2p3.fr/lavoisier/template.xsd">
    <head>
        <meta charset="utf-8"></meta>
        <meta content="width=device-width, initial-scale=1" name="viewport"></meta>
        <meta content="ie=edge" http-equiv="x-ua-compatible"></meta>

        <title>ARGO | Home</title>



        <xsl:comment> Font Awesome Icons </xsl:comment>
        <link href="/resource/app/html/adminlte/plugins/font-awesome/css/all.css" rel="stylesheet"></link>
        <xsl:comment> IonIcons </xsl:comment>
        <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet"></link>
        <xsl:comment> Theme style </xsl:comment>
        <link href="/resource/app/html/adminlte/dist/css/adminlte-eosc.css" rel="stylesheet"></link>
        <xsl:comment> Google Font: Source Sans Pro </xsl:comment>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet"></link>


    </head>

    <body class="hold-transition sidebar-mini ">
        <div class="wrapper">
            <xsl:comment> Navbar </xsl:comment>
            <nav class="main-header navbar navbar-expand navbar-light bg-white border-bottom">
                <xsl:comment> Left navbar links </xsl:comment>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
                    </li>

                    <li class="nav-item d-none d-sm-inline-block">
                        <a class="nav-link" href="mailto:argo-dev@egi.eu">Contact</a>
                    </li>
                </ul>



                <xsl:comment> Right navbar links </xsl:comment>
                <ul class="navbar-nav ml-auto">
                    <xsl:comment> Messages Dropdown Menu </xsl:comment>

                </ul>
            </nav>
            <xsl:comment> /.navbar </xsl:comment>

            <xsl:comment> Main Sidebar Container </xsl:comment>
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <xsl:comment> Brand Logo </xsl:comment>
                <a class="brand-link" href="/">
                    <img alt="ARGO Logo" class="brand-image img-circle elevation-3" src="/resource/app/img/logo-argo.png" style="opacity: .8"></img>
                    <span class="brand-text">ARGO</span>
                </a>

                <xsl:comment> Sidebar </xsl:comment>
                <div class="sidebar">


                    <xsl:comment> Sidebar Menu </xsl:comment>
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-accordion="false" data-widget="treeview" role="menu">
                            <xsl:comment> Add icons to the links using the .nav-icon class
                                with font-awesome or any other icon font library </xsl:comment>


                            <li class="nav-item">
                                <a class="nav-link" href="http://{$egi.instance}">
                                    <i class="nav-icon far fa-circle text-blue"></i>
                                    <p>EGI ARGO</p>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="http://{$eudat.instance}">
                                    <i class="nav-icon far fa-circle text-warning"></i>
                                    <p>EUDAT ARGO</p>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="http://{$sdc.instance}">
                                    <i class="nav-icon far fa-circle text-success"></i>
                                    <p>SDC ARGO</p>
                                </a>
                            </li>

                            <li class="nav-header">ABOUT ARGO</li>

                            <li class="nav-item">
                                <a class="nav-link" href="https://adminlte.io/docs">
                                    <i class="nav-icon fa fa-book"></i>
                                    <p>Documentation</p>
                                </a>
                            </li>


                        </ul>
                    </nav>
                    <xsl:comment> /.sidebar-menu </xsl:comment>
                </div>
                <xsl:comment> /.sidebar </xsl:comment>
            </aside>

            <xsl:comment> Content Wrapper. Contains page content </xsl:comment>
            <div class="content-wrapper">

                <xsl:comment> Content Header (Page header) </xsl:comment>
                <section class="content-header">
                    <div class="container-fluid">
                        <div class="row mb-2">
                            <div class="col-sm-6">

                            </div>

                        </div>
                    </div><xsl:comment> /.container-fluid </xsl:comment>
                </section>



                <xsl:comment> Main content </xsl:comment>
                <section class="content">



                    <xsl:for-each select="error[not(contains(text(),&apos;No results found for given query&apos;))]"><div class="col-lg-9 col-9">
                        <xsl:comment> small card </xsl:comment>
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>ERROR #<xsl:value-of select="@code"></xsl:value-of></h3>
                                <code>This page isn't available.  </code><br></br><br></br>
                                <code><small><xsl:value-of select="text()"></xsl:value-of></small></code>
                                <code><small><xsl:value-of select="message/text()"></xsl:value-of></small></code>
                                <code><small><xsl:value-of select="details/text()"></xsl:value-of></small></code>
                            </div>
                            <div class="icon">
                                <i class="ion ion-alert"></i>
                            </div>
                            <a class="small-box-footer" href="/">
                                HomePage <i class="fa fa-arrow-circle-right"></i>
                            </a>
                        </div>


                    </div></xsl:for-each>

                    <xsl:for-each select="error[contains(text(),&apos;No results found for given query&apos;)]"><div class="col-lg-9 col-9">
                        <xsl:comment> small card </xsl:comment>
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>Empty Dataset</h3>
                                <code>This query doesn't return any results, please try with different parameters </code>

                            </div>
                            <div class="icon">
                                <i class="ion ion-alert"></i>
                            </div>
                            <a class="small-box-footer" href="/">
                                HomePage <i class="fa fa-arrow-circle-right"></i>
                            </a>
                        </div>


                    </div></xsl:for-each>



                    <xsl:comment> /.error-page </xsl:comment>
                </section>
                <xsl:comment> /.content </xsl:comment>
            </div>
            <xsl:comment> /.content-wrapper </xsl:comment>
            <xsl:comment> Main Footer </xsl:comment>
            <footer class="main-footer">
                <xsl:comment> To the right </xsl:comment>
                <div class="float-right  d-sm-block-down">
                    <strong>Copyright  2019 <a href="https://www.eosc-hub.eu/">EOSC-Hub</a>.</strong>
                </div>
                <xsl:comment> Default to the left </xsl:comment>
                EOSC-hub receives funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 777536.
            </footer>
        </div>
        <xsl:comment> ./wrapper </xsl:comment>

        <xsl:comment> REQUIRED SCRIPTS </xsl:comment>

        <xsl:comment> jQuery </xsl:comment>
        <script src="/resource/app/html/adminlte/plugins/jquery/jquery.min.js"></script>
        <xsl:comment> Bootstrap </xsl:comment>
        <script src="/resource/app/html/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <xsl:comment> AdminLTE </xsl:comment>
        <script src="/resource/app/html/adminlte/dist/js/adminlte.js"></script>

        <xsl:comment> OPTIONAL SCRIPTS </xsl:comment>
        <script src="/resource/app/html/adminlte/plugins/chart.js/Chart.min.js"></script>
        <script src="/resource/app/html/adminlte/dist/js/demo.js"></script>
        <script src="/resource/app/html/adminlte/dist/js/pages/dashboard3.js"></script>
    </body>
</html></xsl:template><xsl:template name="process-token"><xsl:param name="token"></xsl:param><xsl:param name="position"></xsl:param><xsl:param name="last"></xsl:param><xsl:param name="callback"></xsl:param><xsl:choose><xsl:when test="false()"></xsl:when></xsl:choose></xsl:template><xsl:template name="tokenize">
    <xsl:param name="string"></xsl:param>
    <xsl:param name="delimiter"></xsl:param>
    <xsl:param name="callback"></xsl:param>
    <xsl:param name="position">1</xsl:param>
    <xsl:choose>
        <xsl:when test="contains($string, $delimiter)">
            <xsl:call-template name="process-token">
                <xsl:with-param name="token" select="substring-before($string, $delimiter)"></xsl:with-param>
                <xsl:with-param name="position" select="$position"></xsl:with-param>
                <xsl:with-param name="last" select="false()"></xsl:with-param>
                <xsl:with-param name="callback" select="$callback"></xsl:with-param>
            </xsl:call-template>
            <xsl:call-template name="tokenize">
                <xsl:with-param name="string" select="substring-after($string, $delimiter)"></xsl:with-param>
                <xsl:with-param name="delimiter" select="$delimiter"></xsl:with-param>
                <xsl:with-param name="callback" select="$callback"></xsl:with-param>
                <xsl:with-param name="position" select="$position + 1"></xsl:with-param>
            </xsl:call-template>
        </xsl:when>
        <xsl:otherwise>
            <xsl:call-template name="process-token">
                <xsl:with-param name="token" select="$string"></xsl:with-param>
                <xsl:with-param name="position" select="$position"></xsl:with-param>
                <xsl:with-param name="last" select="true()"></xsl:with-param>
                <xsl:with-param name="callback" select="$callback"></xsl:with-param>
            </xsl:call-template>
        </xsl:otherwise>
    </xsl:choose>
</xsl:template><xsl:template match="*" mode="serialize">
    <xsl:param name="indent"><xsl:text>
</xsl:text></xsl:param>
    <xsl:if test="string-length($indent)&gt;1"><xsl:value-of select="$indent"></xsl:value-of></xsl:if>&lt;<xsl:value-of select="name()"></xsl:value-of>
    <xsl:apply-templates mode="serialize" select="@*"></xsl:apply-templates>
    <xsl:choose>
        <xsl:when test="*">&gt;<xsl:text></xsl:text>
            <xsl:apply-templates mode="serialize"><xsl:with-param name="indent" select="concat($indent,&apos;    &apos;)"></xsl:with-param></xsl:apply-templates>
            <xsl:value-of select="$indent"></xsl:value-of>&lt;/<xsl:value-of select="name()"></xsl:value-of>&gt;<xsl:text></xsl:text>
        </xsl:when>
        <xsl:when test="text()|comment()">&gt;<xsl:apply-templates mode="serialize"></xsl:apply-templates>&lt;/<xsl:value-of select="name()"></xsl:value-of>&gt;</xsl:when>
        <xsl:otherwise>/&gt;</xsl:otherwise>
    </xsl:choose>
</xsl:template><xsl:template match="@*" mode="serialize">
    <xsl:text> </xsl:text><xsl:value-of select="name()"></xsl:value-of>="<xsl:value-of select="."></xsl:value-of>"<xsl:text></xsl:text>
</xsl:template><xsl:template match="text()" mode="serialize">
    <xsl:value-of select="normalize-space(.)"></xsl:value-of>
</xsl:template><xsl:template match="comment()" mode="serialize">
    <xsl:comment><xsl:value-of select="."></xsl:value-of></xsl:comment>
</xsl:template></xsl:stylesheet>