<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><!-- generated by module html-template-engine --><xsl:output method="html"></xsl:output><xsl:variable name="app.version">2.0.3</xsl:variable><xsl:template match="/"><html lang="en" xmlns:tpl="http://software.in2p3.fr/lavoisier/template.xsd">

    <head>
        <meta charset="utf-8"></meta>
        <meta content="width=device-width, initial-scale=1" name="viewport"></meta>
        <meta content="ie=edge" http-equiv="x-ua-compatible"></meta>

        <title>ARGO | Home</title>



        <xsl:comment> Font Awesome Icons </xsl:comment>
        <link href="/resource/app/html/adminlte/plugins/font-awesome/css/font-awesome.min.css?v={$app.version}" rel="stylesheet"></link>
        <xsl:comment> IonIcons </xsl:comment>
        <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css?v={$app.version}" rel="stylesheet"></link>
        <xsl:comment> Theme style </xsl:comment>
        <xsl:choose><xsl:when test="root/@tenant"><link href="/resource/app/html/adminlte/dist/css/adminlte-{root/@tenant}.css?v={$app.version}" rel="stylesheet"></link></xsl:when><xsl:otherwise><link href="/resource/app/html/adminlte/dist/css/adminlte-eosc.css?v={$app.version}" rel="stylesheet"></link></xsl:otherwise></xsl:choose>

        <xsl:comment> Google Font: Source Sans Pro </xsl:comment>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet"></link>

        <link href="/resource/app/css/argo-eosc.css?v={$app.version}" rel="stylesheet"></link>
        <link href="/resource/app/css/flags.css?v={$app.version}" rel="stylesheet" type="text/css"></link>



    </head>

    <body class="hold-transition sidebar-mini ">
        <div class="wrapper">
            <xsl:comment> Navbar </xsl:comment>
            <nav class="main-header navbar navbar-expand navbar-light bg-white border-bottom">
                <xsl:comment> Left navbar links </xsl:comment>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
                    </li>
                    <li class="nav-item d-none d-sm-inline-block">
                        <a class="nav-link" href="/{root/@tenant}">Home</a>
                    </li>
                    <li class="nav-item d-none d-sm-inline-block">
                        <a class="nav-link" href="mailto:argo-dev@egi.eu">Contact</a>
                    </li>
                </ul>



                <xsl:comment> Right navbar links </xsl:comment>
                <ul class="navbar-nav ml-auto">
                    <xsl:comment> Messages Dropdown Menu </xsl:comment>

                </ul>
            </nav>
            <xsl:comment> /.navbar </xsl:comment>

            <xsl:comment> Main Sidebar Container </xsl:comment>
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <xsl:comment> Brand Logo </xsl:comment>
                <a class="brand-link" href="/{root/@tenant}">
                    <img alt="ARGO Logo" class="brand-image img-circle elevation-2" src="/resource/app/img/logo-argo.png" style="opacity: .8"></img>
                    <span class="brand-text">ARGO</span>
                </a>

                <xsl:comment> Sidebar </xsl:comment>
                <div class="sidebar font-weight-light">


                    <xsl:comment> Sidebar Menu </xsl:comment>
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-accordion="false" data-widget="treeview" role="menu">
                            <xsl:comment> Add icons to the links using the .nav-icon class
                                with font-awesome or any other icon font library </xsl:comment>
                            <li class="nav-item has-treeview menu-open">


                                <xsl:choose><xsl:when test="root/@tenant and root/@report"><ul class="nav nav-treeview sidebar-collapse" style="list-style:none;padding:0;margin:0">

                                    <li class="nav-item">
                                        <p>
                                            <xsl:choose><xsl:when test="/root/@tenant=&apos;egi&apos;"><select class="custom-select" id="profiles">
                                                <xsl:choose><xsl:when test="/root/@report=&apos;Critical&apos;"><option selected="true" value="/egi">EGI - Critical</option></xsl:when><xsl:otherwise><option value="/egi">EGI - Critical</option></xsl:otherwise></xsl:choose>


                                                <xsl:choose><xsl:when test="/root/@report=&apos;OPS-MONITOR-Critical&apos;"><option selected="true" value="/egi/OPS-MONITOR-Critical">EGI - OPSMONITOR-Critical</option></xsl:when><xsl:otherwise><option value="/egi/OPS-MONITOR-Critical">EGI - OPSMONITOR-Critical</option></xsl:otherwise></xsl:choose>

                                            </select></xsl:when></xsl:choose>


                                            <xsl:choose><xsl:when test="/root/@tenant=&apos;eudat&apos;"><select class="custom-select" id="profiles">
                                                <xsl:choose><xsl:when test="root/@tenant=&apos;eudat&apos;"><option selected="true" value="/eudat">EUDAT - Critical</option></xsl:when></xsl:choose>
                                            </select></xsl:when></xsl:choose>
                                        </p>


                                    </li>

                                    <xsl:choose><xsl:when test="count(/root/report/endpoint_group_list/item/text())&gt;1reportDetails"><li class="nav-item">
                                        <p>
                                            <select class="custom-select" id="servicesGroup">
                                                <xsl:choose><xsl:when test="/root/@tenant=&apos;eudat&apos;"><option disabled="true" selected="true">--Select your service group --</option></xsl:when></xsl:choose>
                                                <xsl:choose><xsl:when test="/root/@tenant=&apos;egi&apos;"><option disabled="true" selected="true">--Select your site --</option></xsl:when></xsl:choose>
                                                <xsl:for-each select="/root/report/endpoint_group_list/item/text()"><option value="/{/root/@tenant}/dashboard/{/root/@report}/{.}"><xsl:value-of select="."></xsl:value-of></option></xsl:for-each>
                                            </select>


                                        </p>

                                    </li></xsl:when></xsl:choose>
                                </ul></xsl:when></xsl:choose>




                                <xsl:choose><xsl:when test="root/@tenant=&apos;egi&apos; and root/@report=&apos;Critical&apos;"><ul class="nav nav-treeview">
                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/egi/Critical">
                                            <i class="fa fa-eye nav-icon"></i>
                                            <p>Dashboard</p>
                                        </a>
                                    </li></xsl:for-each>
                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/egi/report-ar/Critical/NGI">
                                            <i class="fa fa-tachometer nav-icon"></i>
                                            <p>Availability/Reliability</p>
                                        </a>
                                    </li></xsl:for-each>

                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/egi/report-status/Critical/SITES">
                                            <i class="fa fa-check-circle  nav-icon"></i>
                                            <p>Status</p>
                                        </a>
                                    </li></xsl:for-each>

                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/egi/Critical/custom">
                                            <i class="fa fa fa-file nav-icon"></i>
                                            <p>Custom Report</p>
                                        </a>
                                    </li></xsl:for-each>
                                </ul></xsl:when></xsl:choose>

                                <xsl:choose><xsl:when test="root/@tenant=&apos;egi&apos; and root/@report=&apos;OPS-MONITOR-Critical&apos;"><ul class="nav nav-treeview">
                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/egi/OPS-MONITOR-Critical">
                                            <i class="fa fa-eye nav-icon"></i>
                                            <p>Dashboard</p>
                                        </a>
                                    </li></xsl:for-each>
                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/egi/report-ar/OPS-MONITOR-Critical/NGI">
                                            <i class="fa fa-tachometer nav-icon"></i>
                                            <p>Availability/Reliability</p>
                                        </a>
                                    </li></xsl:for-each>

                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/egi/report-status/OPS-MONITOR-Critical/SITES">
                                            <i class="fa fa-check-circle nav-icon"></i>
                                            <p>Status</p>
                                        </a>
                                    </li></xsl:for-each>

                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/egi/OPS-MONITOR-Critical/custom">
                                            <i class="fa fa fa-file nav-icon"></i>
                                            <p>Custom Report</p>
                                        </a>
                                    </li></xsl:for-each>

                                </ul></xsl:when></xsl:choose>

                                <xsl:choose><xsl:when test="root/@tenant=&apos;eudat&apos; and root/@report=&apos;Critical&apos;"><ul class="nav nav-treeview">
                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/eudat/Critical">
                                            <i class="fa fa-eye nav-icon"></i>
                                            <p>Dashboard</p>
                                        </a>
                                    </li></xsl:for-each>
                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/eudat/report-ar/Critical/SERVICEGROUPS">
                                            <i class="fa fa-tachometer nav-icon"></i>
                                            <p>Availability/Reliability</p>
                                        </a>
                                    </li></xsl:for-each>

                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/eudat/report-status/Critical/SERVICEGROUPS">
                                            <i class="fa fa-check-circle  nav-icon"></i>
                                            <p>Status</p>
                                        </a>
                                    </li></xsl:for-each>

                                    <xsl:for-each select="/root"><li class="nav-item">
                                        <a class="nav-link" href="/eudat/Critical/custom">
                                            <i class="fa fa fa-file nav-icon"></i>
                                            <p>Custom Report</p>
                                        </a>
                                    </li></xsl:for-each>

                                </ul></xsl:when></xsl:choose>


                            </li>

                            <li class="nav-header"><h5>ABOUT ARGO</h5></li>
                            <li class="nav-item">
                                <a class="nav-link" href="http://argoeu.github.io/overview">
                                    <i class="nav-icon fa fa-book"> </i>
                                    <p> Documentation</p>
                                </a>
                            </li>

                            <xsl:choose><xsl:when test="root/@tenant=&apos;egi&apos;"><li class="nav-item">
                                <a class="nav-link" href="/termsofUse">
                                    <i class="nav-icon fa fa-handshake-o"> </i>
                                    <p> Terms of Use</p>
                                </a>
                            </li></xsl:when></xsl:choose>
                            <br></br> <br></br> <br></br>

                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="nav-icon fa fa-circle-o text-success"> </i>
                                    <p class="text"> <xsl:value-of select="$app.version"></xsl:value-of></p>
                                </a>
                            </li>


                        </ul>
                    </nav>
                    <xsl:comment> /.sidebar-menu </xsl:comment>
                </div>



                <xsl:comment> /.sidebar </xsl:comment>
            </aside>
            <xsl:comment> /sidebar </xsl:comment>

            <xsl:comment> Content Wrapper. Contains page content </xsl:comment>
            <div class="content-wrapper">
                <xsl:comment> Content Header (Page header) </xsl:comment>
                <div class="content-header">
                    <div class="container-fluid">
                        <div class="row mb-2">

                            <div class="col-sm-7">

                            </div><xsl:comment> /.col </xsl:comment>

                            <div class="col-sm-5">
                                <ol class="breadcrumb float-sm-right">
                                    <li class="breadcrumb-item"><a href="/{root/@tenant}">Home</a></li>
                                    <li class="breadcrumb-item">Dashboard</li>
                                    <xsl:choose><xsl:when test="root/@details=&apos;level0&apos;"><li class="breadcrumb-item active"><a href="/{root/@tenant}/{root/@report}"><xsl:value-of select="root/@tenant"></xsl:value-of> - <xsl:value-of select="root/@report"></xsl:value-of></a></li></xsl:when><xsl:otherwise><li class="breadcrumb-item active"><a href="/{root/@tenant}/{root/@report}"><xsl:value-of select="root/@tenant"></xsl:value-of> - <xsl:value-of select="root/@report"></xsl:value-of></a></li></xsl:otherwise></xsl:choose>

                                    <xsl:choose><xsl:when test="root/@details=&apos;level1&apos;"><li class="breadcrumb-item active"><a href="/{root/@tenant}/dashboard/{root/@report}/{root/@group}"><xsl:value-of select="root/@group"></xsl:value-of></a></li></xsl:when></xsl:choose>
                                </ol>
                            </div><xsl:comment> /.col </xsl:comment>
                        </div><xsl:comment> /.row </xsl:comment>
                    </div><xsl:comment> /.container-fluid </xsl:comment>
                </div>


                <xsl:comment> Main content </xsl:comment>
                <div class="content">
                    <div class="container-fluid">

                        <div class="row">

                            <xsl:choose><xsl:when test="root/@details!=&apos;level1&apos;"><div class="col-3">
                                <div>
                                    <xsl:comment> Widget: user widget style 1 </xsl:comment>

                                    <div class="card card-widget widget-user-2">
                                        <xsl:comment> Add the bg color to the header using any of the bg-* classes </xsl:comment>
                                        <div class="widget-user-header border ">
                                            <div class="widget-user-image">
                                                <img alt="Logo" class="img-circle elevation-2" height="160px" src="/resource/app/img/logo-{root/@tenant}.png" width="160px"></img>
                                            </div>
                                            <xsl:comment> /.widget-user-image </xsl:comment>
                                            <h3 class="widget-user-username text-uppercase"><xsl:value-of select="/root/@tenant"></xsl:value-of></h3>
                                            <h5 class="widget-user-desc"><xsl:value-of select="/root/report/@description"></xsl:value-of></h5>
                                        </div>
                                        <div class="card-body">
                                            <xsl:for-each select="/root/report"><ul class="nav flex-column">
                                                <li class="nav-item">
                                                    <a class="nav-link" data-target="#{group_type/text()}" data-toggle="modal" href="#">
                                                        <xsl:value-of select="group_type/text()"></xsl:value-of><span class="float-right badge bg-primary"><xsl:value-of select="group_count/text()"></xsl:value-of> </span>
                                                    </a>


                                                    <xsl:comment> Modal </xsl:comment>
                                                    <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="{group_type/text()}" role="dialog" tabindex="-1">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title"><xsl:value-of select="group_type/text()"></xsl:value-of> List</h5>
                                                                    <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                                                                        <span aria-hidden="true">x</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <ul>
                                                                        <xsl:for-each select="/root/report/group_list/item/text()"><li><xsl:value-of select="."></xsl:value-of></li></xsl:for-each>
                                                                    </ul>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button class="btn btn-primary" data-dismiss="modal" type="button">Close</button>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                </li>

                                                <li>
                                                    <a class="nav-link" data-target="#{endpoint_group_type/text()}" data-toggle="modal" href="#">
                                                        <xsl:value-of select="endpoint_group_type/text()"></xsl:value-of><span class="float-right badge bg-primary"><xsl:value-of select="endpoint_group_count/text()"></xsl:value-of> </span>
                                                    </a>
                                                    <xsl:comment> Modal </xsl:comment>
                                                    <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="{endpoint_group_type/text()}" role="dialog" tabindex="-1">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title"><xsl:value-of select="endpoint_group_type/text()"></xsl:value-of> List</h5>
                                                                    <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                                                                        <span aria-hidden="true">x</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <ul>
                                                                        <xsl:for-each select="/root/report/endpoint_group_list/item/text()"><li><xsl:value-of select="."></xsl:value-of></li></xsl:for-each>
                                                                    </ul>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button class="btn btn-primary" data-dismiss="modal" type="button">Close</button>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li>
                                                    <a class="nav-link" data-target="#services" data-toggle="modal" href="#">
                                                        SERVICE TYPES<span class="float-right badge bg-primary"><xsl:value-of select="service_count/text()"></xsl:value-of> </span>
                                                    </a>
                                                    <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="services" role="dialog" tabindex="-1">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title">Service Types List</h5>
                                                                    <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                                                                        <span aria-hidden="true">x</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <ul>
                                                                        <xsl:for-each select="/root/report/service_list/item/text()"><li><xsl:value-of select="."></xsl:value-of></li></xsl:for-each>
                                                                    </ul>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button class="btn btn-primary" data-dismiss="modal" type="button">Close</button>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                </li>
                                            </ul></xsl:for-each>
                                        </div>
                                    </div>


                                    <xsl:comment> /.row </xsl:comment>
                                </div>
                                <div class="row">


                                    <xsl:comment> small card </xsl:comment>
                                    <div class="col-md-6">

                                        <xsl:choose><xsl:when test="/root/report-ar/@availability &gt;= 80"><div class="info-box">
                                            <span class="info-box-icon bg-success"><i class="ion ion-stats-bars"></i></span>

                                            <div class="info-box-content">
                                                <xsl:choose><xsl:when test="root/@details=&apos;level0&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar/{/root/@report}/{/root/@topology}">Availability</a></span></xsl:when></xsl:choose>
                                                <xsl:choose><xsl:when test="root/@details=&apos;level1&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar-group-details/{/root/@report}/{/root/@topology}/{/root/@group}">Availability</a></span></xsl:when></xsl:choose>
                                                <span class="info-box-number"><xsl:value-of select="/root/report-ar/@availability"></xsl:value-of></span>
                                            </div>
                                            <xsl:comment> /.info-box-content </xsl:comment>
                                        </div></xsl:when><xsl:otherwise><div class="info-box">
                                            <span class="info-box-icon bg-success"><i class="ion ion-stats-bars"></i></span>

                                            <div class="info-box-content">
                                                <xsl:choose><xsl:when test="root/@details=&apos;level0&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar/{/root/@report}/{/root/@topology}">Availability</a></span></xsl:when></xsl:choose>
                                                <xsl:choose><xsl:when test="root/@details=&apos;level1&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar-group-details/{/root/@report}/{/root/@topology}/{/root/@group}">Availability</a></span></xsl:when></xsl:choose>

                                                <span class="info-box-number"><xsl:value-of select="/root/report-ar/@availability"></xsl:value-of></span>
                                            </div>
                                            <xsl:comment> /.info-box-content </xsl:comment>
                                        </div></xsl:otherwise></xsl:choose>



                                    </div>

                                    <div class="col-md-6">

                                        <xsl:choose><xsl:when test="/root/report-ar/@reliability &gt;= 85"><div class="info-box">
                                            <span class="info-box-icon bg-success"><i class="ion ion-stats-bars"></i></span>

                                            <div class="info-box-content">
                                                <xsl:choose><xsl:when test="/root/@details=&apos;level0&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar/{/root/@report}/{/root/@topology}">Reliability</a></span></xsl:when></xsl:choose>
                                                <xsl:choose><xsl:when test="/root/@details=&apos;level1&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar-group-details/{/root/@report}/{/root/@topology}/{/root/@group}">Reliability</a></span></xsl:when></xsl:choose>

                                                <span class="info-box-number"><xsl:value-of select="/root/report-ar/@reliability"></xsl:value-of></span>
                                            </div>
                                            <xsl:comment> /.info-box-content </xsl:comment>
                                        </div></xsl:when><xsl:otherwise><div class="info-box">
                                            <span class="info-box-icon bg-success"><i class="ion ion-stats-bars"></i></span>

                                            <div class="info-box-content">
                                                <xsl:choose><xsl:when test="/root/@details=&apos;level0&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar/{/root/@report}/{/root/@topology}">Reliability</a></span></xsl:when></xsl:choose>
                                                <xsl:choose><xsl:when test="/root/@details=&apos;level1&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar-group-details/{/root/@report}/{/root/@topology}/{/root/@group}">Reliability</a></span></xsl:when></xsl:choose>

                                                <span class="info-box-number"><xsl:value-of select="/root/report-ar/@reliability"></xsl:value-of></span>
                                            </div>
                                            <xsl:comment> /.info-box-content </xsl:comment>
                                        </div></xsl:otherwise></xsl:choose>




                                    </div>





                                </div>

                            </div></xsl:when><xsl:otherwise><div class="col-3">
                                <div>
                                    <xsl:comment> Widget: user widget style 1 </xsl:comment>

                                    <xsl:choose><xsl:when test="/root/@tenant=&apos;egi&apos;"><div class="card card-widget">
                                        <div class="card-header">
                                            <span class="card-title"><xsl:value-of select="/root/SITE/@NAME"></xsl:value-of></span>
                                        </div>
                                        <div class="card-body">
                                            <h5><span class="m-1"><xsl:value-of select="/root/SITE/OFFICIAL_NAME/text()"></xsl:value-of></span>  <img alt="{/root/SITE/COUNTRY/text()}" class="flag flag-{/root/SITE/COUNTRY_CODE/text()}" src="/resource/app/css/blank.gif"></img></h5>

                                            <ul class="list-group list-group-flush">
                                                <li class="list-group-item">PRODUCTION
                                                    <xsl:choose><xsl:when test="/root/SITE/PRODUCTION_INFRASTRUCTURE/text()=&apos;Production&apos;"><i class="fa fa-check-circle text-success"></i></xsl:when><xsl:otherwise><i class="fa fa-times-circle text-danger"></i></xsl:otherwise></xsl:choose>


                                                </li>
                                                <li class="list-group-item">CERTIFIED
                                                    <xsl:choose><xsl:when test="/root/SITE/CERTIFICATION_STATUS/text()=&apos;Certified&apos;"><i class="fa fa-check-circle text-success"></i></xsl:when><xsl:otherwise><i class="fa fa-times-circle text-danger"></i></xsl:otherwise></xsl:choose>

                                                </li>
                                                <li class="list-group-item">NOTIFICATIONS
                                                    <xsl:choose><xsl:when test="/root/SITE/NOTIFICATIONS/text()=&apos;TRUE&apos;"><i class="fa fa-check-circle text-success"></i></xsl:when><xsl:otherwise><i class="fa fa-times-circle text-danger"></i></xsl:otherwise></xsl:choose>

                                                </li>
                                            </ul>

                                        </div>
                                    </div></xsl:when></xsl:choose>

                                    <xsl:choose><xsl:when test="/root/@tenant=&apos;eudat&apos;"><div class="card card-widget">
                                        <div class="card-header">
                                            <span class="card-title"><xsl:value-of select="root/SERVICE_GROUP/NAME/text()"></xsl:value-of></span>
                                        </div>
                                        <div class="card-body">
                                            <h5><xsl:value-of select="/root/SERVICE_GROUP/DESCRIPTION/text()"></xsl:value-of></h5>
                                            <ul class="list-group list-group-flush">
                                                <xsl:for-each select="/root/SERVICE_GROUP/SERVICE_ENDPOINT"><li class="list-group-item">
                                                    <xsl:value-of select="HOSTNAME/text()"></xsl:value-of>  <a href="{URL/text()}"><i class="fa fa-link m-1"></i></a>  <a href="{DPMT_URL/text()}"><i class="fa fa-external-link m-1"></i></a>
                                                </li></xsl:for-each>
                                            </ul>


                                        </div>
                                    </div></xsl:when></xsl:choose>

                                </div>
                                <div class="row">


                                    <xsl:comment> small card </xsl:comment>
                                    <div class="col-md-6">

                                        <xsl:choose><xsl:when test="/root/report-ar/@availability &gt;= 80"><div class="info-box">
                                            <span class="info-box-icon bg-success"><i class="ion ion-stats-bars"></i></span>

                                            <div class="info-box-content">
                                                <xsl:choose><xsl:when test="root/@details=&apos;level0&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar/{/root/@report}/{/root/@topology}">Availability</a></span></xsl:when></xsl:choose>
                                                <xsl:choose><xsl:when test="root/@details=&apos;level1&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar-group-details/{/root/@report}/{/root/@topology}/{/root/@group}">Availability</a></span></xsl:when></xsl:choose>
                                                <span class="info-box-number"><xsl:value-of select="/root/report-ar/@availability"></xsl:value-of></span>
                                            </div>
                                            <xsl:comment> /.info-box-content </xsl:comment>
                                        </div></xsl:when><xsl:otherwise><div class="info-box">
                                            <span class="info-box-icon bg-success"><i class="ion ion-stats-bars"></i></span>

                                            <div class="info-box-content">
                                                <xsl:choose><xsl:when test="root/@details=&apos;level0&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar/{/root/@report}/{/root/@topology}">Availability</a></span></xsl:when></xsl:choose>
                                                <xsl:choose><xsl:when test="root/@details=&apos;level1&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar-group-details/{/root/@report}/{/root/@topology}/{/root/@group}">Availability</a></span></xsl:when></xsl:choose>

                                                <span class="info-box-number"><xsl:value-of select="/root/report-ar/@availability"></xsl:value-of></span>
                                            </div>
                                            <xsl:comment> /.info-box-content </xsl:comment>
                                        </div></xsl:otherwise></xsl:choose>



                                    </div>

                                    <div class="col-md-6">

                                        <xsl:choose><xsl:when test="/root/report-ar/@reliability &gt;= 85"><div class="info-box">
                                            <span class="info-box-icon bg-success"><i class="ion ion-stats-bars"></i></span>

                                            <div class="info-box-content">
                                                <xsl:choose><xsl:when test="/root/@details=&apos;level0&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar/{/root/@report}/{/root/@topology}">Reliability</a></span></xsl:when></xsl:choose>
                                                <xsl:choose><xsl:when test="/root/@details=&apos;level1&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar-group-details/{/root/@report}/{/root/@topology}/{/root/@group}">Reliability</a></span></xsl:when></xsl:choose>

                                                <span class="info-box-number"><xsl:value-of select="/root/report-ar/@reliability"></xsl:value-of></span>
                                            </div>
                                            <xsl:comment> /.info-box-content </xsl:comment>
                                        </div></xsl:when><xsl:otherwise><div class="info-box">
                                            <span class="info-box-icon bg-success"><i class="ion ion-stats-bars"></i></span>

                                            <div class="info-box-content">
                                                <xsl:choose><xsl:when test="/root/@details=&apos;level0&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar/{/root/@report}/{/root/@topology}">Reliability</a></span></xsl:when></xsl:choose>
                                                <xsl:choose><xsl:when test="/root/@details=&apos;level1&apos;"><span class="info-box-text"><a href="/{/root/@tenant}/report-ar-group-details/{/root/@report}/{/root/@topology}/{/root/@group}">Reliability</a></span></xsl:when></xsl:choose>

                                                <span class="info-box-number"><xsl:value-of select="/root/report-ar/@reliability"></xsl:value-of></span>
                                            </div>
                                            <xsl:comment> /.info-box-content </xsl:comment>
                                        </div></xsl:otherwise></xsl:choose>




                                    </div>





                                </div>

                            </div></xsl:otherwise></xsl:choose>

                            <div class="col-9">
                                <div class="row">




                                    <div class="col-7">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="card-title">Availability/Reliability - Last 10 days</h3>

                                                <div class="card-tools">
                                                    <button class="btn btn-tool" data-widget="collapse" type="button"><i class="fa fa-minus"></i>
                                                    </button>
                                                    <button class="btn btn-tool" data-widget="remove" type="button"><i class="fa fa-times"></i>
                                                    </button>
                                                </div>
                                            </div>

                                            <div class="card-body">
                                                <xsl:for-each select="/root/report-ar/*"><div class="d-none dataAvailability"><xsl:value-of select="@availability"></xsl:value-of></div></xsl:for-each>
                                                <xsl:for-each select="/root/report-ar/*"><div class="d-none dataReliability"><xsl:value-of select="@reliability"></xsl:value-of></div></xsl:for-each>
                                                <xsl:for-each select="/root/report-ar/*"><div class="d-none dataTimestamp"><xsl:value-of select="substring-after(@timestamp,&apos;-&apos;)"></xsl:value-of></div></xsl:for-each>

                                                <div>

                                                    <div class="chart-responsive">
                                                        <canvas height="160" id="myChart2"></canvas>
                                                    </div>
                                                    <xsl:comment> ./chart-responsive </xsl:comment>

                                                    <xsl:comment> /.col </xsl:comment>

                                                    <xsl:comment> /.col </xsl:comment>
                                                </div>
                                            </div>

                                        </div>

                                    </div>

                                    <div class="col-5">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="card-title">Last statuses</h3>

                                                <div class="card-tools">
                                                    <button class="btn btn-tool" data-widget="collapse" type="button"><i class="fa fa-minus"></i>
                                                    </button>
                                                    <button class="btn btn-tool" data-widget="remove" type="button"><i class="fa fa-times"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <xsl:comment> /.card-header </xsl:comment>
                                            <div class="card-body">

                                                <div class="row">
                                                    <div class="col-md-9">
                                                        <div class="chart-responsive">
                                                            <canvas height="160" id="myChart1"></canvas>
                                                        </div>
                                                        <xsl:comment> ./chart-responsive </xsl:comment>
                                                    </div>
                                                    <xsl:comment> /.col </xsl:comment>
                                                    <div class="clearfix col-md-3">
                                                        <ul class="chart-legend clearfix">

                                                        </ul>
                                                    </div>
                                                    <xsl:comment> /.col </xsl:comment>
                                                </div>
                                                <div class="row">

                                                    <div class="clearfix">
                                                        <br></br>
                                                        <xsl:for-each select="/root/status-last/@*"><div class="d-none dataStatuses"><xsl:value-of select="."></xsl:value-of></div></xsl:for-each>
                                                        <xsl:for-each select="/root/status-last/@*"><div class="d-none labelStatuses"><xsl:value-of select="local-name(.)"></xsl:value-of></div></xsl:for-each>
                                                        <ul style="list-style:none">
                                                            <xsl:for-each select="/root/status-last/@*"><li>
                                                                <xsl:choose><xsl:when test="local-name(.)=&apos;Ok&apos;"><i class="m-1 fa fa-circle-o text-success"></i></xsl:when><xsl:when test="local-name(.)=&apos;Warning&apos;"><i class="m-1 fa fa-circle-o text-warning"></i></xsl:when><xsl:when test="local-name(.)=&apos;Critical&apos;"><i class="m-1 fa fa-circle-o text-danger"></i></xsl:when><xsl:when test="local-name(.)=&apos;Missing&apos;"><i class="m-1 fa fa-circle-o text-info"></i></xsl:when><xsl:otherwise><i class="m-1 fa fa-circle-o text-muted"></i></xsl:otherwise></xsl:choose>




                                                                <xsl:value-of select="local-name(.)"></xsl:value-of> : <xsl:value-of select="."></xsl:value-of>
                                                            </li></xsl:for-each>

                                                        </ul>

                                                    </div>
                                                    <xsl:comment> /.col </xsl:comment>
                                                </div>
                                                <xsl:comment> /.row </xsl:comment>
                                            </div>
                                        </div>


                                    </div>
                                </div>
                            </div>


                        </div>




                        <div class="row">

                            <div class="col-7">
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title">
                                            Last Status Changes
                                        </h3>


                                    </div>
                                    <xsl:comment> /.card-header </xsl:comment>
                                    <div class="card-body font-weight-light">
                                        <div class="table-responsive">
                                            <table class="table  dataTable table-bordered table-condensed">

                                                <thead>
                                                    <tr>
                                                        <th class="text-nowrap">Endpoint Group</th>
                                                        <th>Endpoint</th>
                                                        <th>Metric</th>
                                                        <th>Timestamp</th>
                                                        <th></th>
                                                        <th></th>
                                                    </tr>
                                                </thead>

                                                <tbody>
                                                    <xsl:for-each select="root/status-last/object"><tr>
                                                        <td><xsl:value-of select="endpoint_group/text()"></xsl:value-of></td>
                                                        <td><xsl:value-of select="endpoint/text()"></xsl:value-of></td>
                                                        <td><xsl:value-of select="metric/text()"></xsl:value-of></td>

                                                        <td> <xsl:value-of select="timestamp/text()"></xsl:value-of></td>
                                                        <td>
                                                            <xsl:choose><xsl:when test="status/text()=&apos;OK&apos;"><span class="badge bg-success"><xsl:value-of select="status/text()"></xsl:value-of></span></xsl:when><xsl:when test="status/text()=&apos;WARNING&apos;"><span class="badge bg-warning"> <xsl:value-of select="status/text()"></xsl:value-of></span></xsl:when><xsl:when test="status/text()=&apos;CRITICAL&apos;"><span class="badge bg-danger"> <xsl:value-of select="status/text()"></xsl:value-of></span></xsl:when><xsl:when test="status/text()=&apos;MISSING&apos;"><span class="badge bg-info"> <xsl:value-of select="status/text()"></xsl:value-of></span></xsl:when><xsl:otherwise><span class="badge bg-gray"> <xsl:value-of select="status/text()"></xsl:value-of></span></xsl:otherwise></xsl:choose>




                                                        </td>
                                                        <td>
                                                            <span class="fa fa-search" data-target="#{metric/text()}_{timestamp/text()}" data-toggle="modal"></span>

                                                            <xsl:comment> Modal </xsl:comment>
                                                            <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="{metric/text()}_{timestamp/text()}" role="dialog" tabindex="-1">
                                                                <div class="modal-dialog modal-lg" role="document">
                                                                    <div class="modal-content ">
                                                                        <div class="modal-header">
                                                                            <h5 class="modal-title" id="exampleModalLabel"><xsl:value-of select="endpoint_group/text()"></xsl:value-of>  /  <xsl:value-of select="endpoint/text()"></xsl:value-of> / <xsl:value-of select="metric/text()"></xsl:value-of>
                                                                                <xsl:choose><xsl:when test="status/text()=&apos;OK&apos;"><span class="badge bg-success"><xsl:value-of select="status/text()"></xsl:value-of></span></xsl:when><xsl:when test="status/text()=&apos;WARNING&apos;"><span class="badge bg-warning"> <xsl:value-of select="status/text()"></xsl:value-of></span></xsl:when><xsl:when test="status/text()=&apos;CRITICAL&apos;"><span class="badge bg-danger"> <xsl:value-of select="status/text()"></xsl:value-of></span></xsl:when><xsl:when test="status/text()=&apos;MISSING&apos;"><span class="badge bg-info"> <xsl:value-of select="status/text()"></xsl:value-of></span></xsl:when><xsl:otherwise><span class="badge bg-gray"> <xsl:value-of select="status/text()"></xsl:value-of></span></xsl:otherwise></xsl:choose>




                                                                            </h5>
                                                                            <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                                                                                <span aria-hidden="true">x</span>
                                                                            </button>
                                                                        </div>
                                                                        <div class="modal-body text-justify">
                                                                            <div><p class="font-weight-bold">Timestamp</p> <xsl:value-of select="timestamp/text()"></xsl:value-of></div>

                                                                            <div><p class="font-weight-bold">Summary</p><pre><xsl:value-of select="summary/text()"></xsl:value-of></pre></div>
                                                                            <xsl:choose><xsl:when test="message/text()"><div><p class="font-weight-bold">Message</p><pre><xsl:value-of select="message/text()"></xsl:value-of></pre></div></xsl:when></xsl:choose>
                                                                        </div>
                                                                        <div class="modal-footer">
                                                                            <button class="btn btn-secondary" data-dismiss="modal" type="button">Close</button>

                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr></xsl:for-each>

                                                </tbody>


                                            </table>

                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="col-5">
                                <div class="card">
                                    <div class="card-header">
                                        <xsl:choose><xsl:when test="root/@tenant=&apos;egi&apos; and root/@details!=&apos;level1&apos;"><h3 class="card-title">
                                            OnGoing Downtimes
                                        </h3></xsl:when><xsl:otherwise><h3 class="card-title">
                                            Last Downtimes
                                        </h3></xsl:otherwise></xsl:choose>



                                    </div>
                                    <xsl:comment> /.card-header </xsl:comment>
                                    <div class="card-body font-weight-light">
                                        <div class="table-responsive">

                                            <table class="table  table-bordered table-condensed dataTable">

                                                <thead>
                                                    <tr>
                                                        <th>Site</th>
                                                        <th>Type</th>
                                                        <th>Start (UTC)</th>
                                                        <th>End (UTC)</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>

                                                <tbody>
                                                    <xsl:for-each select="root/downtimes/DOWNTIME"><tr>
                                                        <td class="text-truncate" style="max-width:250px;"><xsl:value-of select="HOSTED_BY/text()"></xsl:value-of></td>
                                                        <td>
                                                            <xsl:choose><xsl:when test="SEVERITY/text()!=&apos;OUTAGE&apos;"><span class="badge bg-success"><xsl:value-of select="SEVERITY/text()"></xsl:value-of></span></xsl:when><xsl:otherwise><span class="badge bg-warning"><xsl:value-of select="SEVERITY/text()"></xsl:value-of></span></xsl:otherwise></xsl:choose>

                                                        </td>

                                                        <td class="text-nowrap"> <xsl:value-of select="FORMATED_START_DATE/text()"></xsl:value-of></td>
                                                        <td class="text-nowrap"><xsl:value-of select="FORMATED_END_DATE/text()"></xsl:value-of></td>
                                                        <td>

                                                            <xsl:comment> Button trigger modal </xsl:comment>
                                                            <span class="fa fa-search" data-target="#{@PRIMARY_KEY}" data-toggle="modal"></span>

                                                            <xsl:comment> Modal </xsl:comment>
                                                            <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="{@PRIMARY_KEY}" role="dialog" tabindex="-1">
                                                                <div class="modal-dialog modal-lg" role="document">
                                                                    <div class="modal-content ">
                                                                        <div class="modal-header">
                                                                            <h5 class="modal-title" id="exampleModalLabel"><xsl:value-of select="@CLASSIFICATION"></xsl:value-of> DOWNTIME : <xsl:value-of select="HOSTED_BY/text()"></xsl:value-of></h5>
                                                                            <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                                                                                <span aria-hidden="true">x</span>
                                                                            </button>
                                                                        </div>
                                                                        <div class="modal-body text-justify">
                                                                            <div><p class="font-weight-bold">Start Date</p> <xsl:value-of select="FORMATED_START_DATE/text()"></xsl:value-of></div>
                                                                            <div><p class="font-weight-bold">End Date</p> <xsl:value-of select="FORMATED_END_DATE/text()"></xsl:value-of></div>
                                                                            <div><p class="font-weight-bold">Description</p><pre><xsl:value-of select="DESCRIPTION/text()"></xsl:value-of></pre></div>
                                                                            <div><p class="font-weight-bold">Affected Endpoints</p><pre><xsl:value-of select="service_endpoints/text()"></xsl:value-of></pre></div>
                                                                        </div>
                                                                        <div class="modal-footer">
                                                                            <button class="btn btn-secondary" data-dismiss="modal" type="button">Close</button>

                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>


                                                        </td>

                                                    </tr></xsl:for-each>

                                                </tbody>


                                            </table>

                                        </div>


                                    </div>

                                </div>
                            </div>

                        </div>



                        <xsl:comment> /.container-fluid </xsl:comment>
                    </div>
                    <xsl:comment> /.content </xsl:comment>
                </div>

            </div>
            <xsl:comment> /.content-wrapper </xsl:comment>
            <xsl:comment> Main Footer </xsl:comment>

            <footer class="main-footer">
                <xsl:comment> To the right </xsl:comment>
                <div class="float-right  d-sm-block-down">
                    <strong>Copyright  2018 <a href="https://www.eosc-hub.eu/">EOSC-Hub</a>.</strong>
                </div>
                <xsl:comment> Default to the left </xsl:comment>
                EOSC-hub receives funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 777536.
            </footer>

        </div>
        <xsl:comment> ./wrapper </xsl:comment>

        <xsl:comment> REQUIRED SCRIPTS </xsl:comment>

        <xsl:comment> jQuery </xsl:comment>
        <script src="/resource/app/html/adminlte/plugins/jquery/jquery.min.js?v={$app.version}"></script>
        <xsl:comment> Bootstrap </xsl:comment>
        <script src="/resource/app/html/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js?v={$app.version}"></script>
        <xsl:comment> adminlte </xsl:comment>
        <script src="/resource/app/html/adminlte/dist/js/adminlte.js?v={$app.version}"></script>

        <xsl:comment> OPTIONAL SCRIPTS </xsl:comment>
        <script src="/resource/app/html/adminlte/plugins/chart.js/Chart.min.js?v={$app.version}"></script>
        <xsl:comment>&lt;script src="/resource/app/html/adminlte/plugins/chart.js/Chart.bundle.min.js"&gt;&lt;/script&gt;</xsl:comment>


        <link href="/resource/app/html/adminlte/plugins/datatables/dataTables.bootstrap.css?v={$app.version}" rel="stylesheet"></link>
        <link href="/resource/app/html/adminlte/plugins/datatables/jquery.dataTables.min.css?v={$app.version}" rel="stylesheet"></link>

        <script src="/resource/app/html/adminlte/plugins/datatables/jquery.dataTables.min.js?v={$app.version}"></script>

        <script src="/resource/app/html/adminlte/plugins/datatables/dataTables.bootstrap.min.js?v={$app.version}"></script>



        <script src="/resource/app/js/dashboard.js?v={$app.version}"></script>





    </body>
</html></xsl:template><xsl:template name="process-token"><xsl:param name="token"></xsl:param><xsl:param name="position"></xsl:param><xsl:param name="last"></xsl:param><xsl:param name="callback"></xsl:param><xsl:choose><xsl:when test="false()"></xsl:when></xsl:choose></xsl:template><xsl:template name="tokenize">
    <xsl:param name="string"></xsl:param>
    <xsl:param name="delimiter"></xsl:param>
    <xsl:param name="callback"></xsl:param>
    <xsl:param name="position">1</xsl:param>
    <xsl:choose>
        <xsl:when test="contains($string, $delimiter)">
            <xsl:call-template name="process-token">
                <xsl:with-param name="token" select="substring-before($string, $delimiter)"></xsl:with-param>
                <xsl:with-param name="position" select="$position"></xsl:with-param>
                <xsl:with-param name="last" select="false()"></xsl:with-param>
                <xsl:with-param name="callback" select="$callback"></xsl:with-param>
            </xsl:call-template>
            <xsl:call-template name="tokenize">
                <xsl:with-param name="string" select="substring-after($string, $delimiter)"></xsl:with-param>
                <xsl:with-param name="delimiter" select="$delimiter"></xsl:with-param>
                <xsl:with-param name="callback" select="$callback"></xsl:with-param>
                <xsl:with-param name="position" select="$position + 1"></xsl:with-param>
            </xsl:call-template>
        </xsl:when>
        <xsl:otherwise>
            <xsl:call-template name="process-token">
                <xsl:with-param name="token" select="$string"></xsl:with-param>
                <xsl:with-param name="position" select="$position"></xsl:with-param>
                <xsl:with-param name="last" select="true()"></xsl:with-param>
                <xsl:with-param name="callback" select="$callback"></xsl:with-param>
            </xsl:call-template>
        </xsl:otherwise>
    </xsl:choose>
</xsl:template><xsl:template match="*" mode="serialize">
    <xsl:param name="indent"><xsl:text>
</xsl:text></xsl:param>
    <xsl:if test="string-length($indent)&gt;1"><xsl:value-of select="$indent"></xsl:value-of></xsl:if>&lt;<xsl:value-of select="name()"></xsl:value-of>
    <xsl:apply-templates mode="serialize" select="@*"></xsl:apply-templates>
    <xsl:choose>
        <xsl:when test="*">&gt;<xsl:text></xsl:text>
            <xsl:apply-templates mode="serialize"><xsl:with-param name="indent" select="concat($indent,&apos;    &apos;)"></xsl:with-param></xsl:apply-templates>
            <xsl:value-of select="$indent"></xsl:value-of>&lt;/<xsl:value-of select="name()"></xsl:value-of>&gt;<xsl:text></xsl:text>
        </xsl:when>
        <xsl:when test="text()|comment()">&gt;<xsl:apply-templates mode="serialize"></xsl:apply-templates>&lt;/<xsl:value-of select="name()"></xsl:value-of>&gt;</xsl:when>
        <xsl:otherwise>/&gt;</xsl:otherwise>
    </xsl:choose>
</xsl:template><xsl:template match="@*" mode="serialize">
    <xsl:text> </xsl:text><xsl:value-of select="name()"></xsl:value-of>="<xsl:value-of select="."></xsl:value-of>"<xsl:text></xsl:text>
</xsl:template><xsl:template match="text()" mode="serialize">
    <xsl:value-of select="normalize-space(.)"></xsl:value-of>
</xsl:template><xsl:template match="comment()" mode="serialize">
    <xsl:comment><xsl:value-of select="."></xsl:value-of></xsl:comment>
</xsl:template></xsl:stylesheet>